/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        kulagreen: "#1db470",
        "kulagreen-dark": "#189d5d",
        kulayellow: "#ffedb3",
        kulabrown: "#ab7f4a",
        kulablue: "#103d71",
        kulapurple: "#7e57c2",
        kulared: "#b2403e",

        // Community revamp design system
        surface: "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#d3daef",
        "surface-variant": "#dce2f7",
        "surface-subtle": "#F9FAFB",
        "surface-container": "#e9edff",
        "surface-container-low": "#f1f3ff",
        "surface-container-high": "#e1e8fd",
        "surface-container-highest": "#dce2f7",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#006d40",
        background: "#f9f9ff",
        "on-background": "#141b2b",
        "on-surface": "#141b2b",
        "on-surface-variant": "#3d4a40",
        "inverse-surface": "#293040",
        "inverse-on-surface": "#edf0ff",
        outline: "#6d7a6f",
        "outline-variant": "#bccabd",

        primary: "#006d40",
        "on-primary": "#ffffff",
        "primary-container": "#1db470",
        "on-primary-container": "#003e22",
        "primary-fixed": "#76fcb0",
        "primary-fixed-dim": "#57de96",
        "on-primary-fixed": "#002110",
        "on-primary-fixed-variant": "#00522f",
        "inverse-primary": "#57de96",

        secondary: "#795900",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffc329",
        "on-secondary-container": "#6f5100",
        "secondary-fixed": "#ffdf9f",
        "secondary-fixed-dim": "#f9bd22",
        "on-secondary-fixed": "#261a00",
        "on-secondary-fixed-variant": "#5c4300",

        tertiary: "#a63743",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#f8757e",
        "on-tertiary-container": "#6e0a1d",
        "tertiary-fixed": "#ffdada",
        "tertiary-fixed-dim": "#ffb3b5",
        "on-tertiary-fixed": "#40000b",
        "on-tertiary-fixed-variant": "#861f2d",

        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",

        "sdg-no-poverty": "#E5243B",
        "sdg-zero-hunger": "#DDA63A",
        "sdg-good-health": "#4C9F38",
        "sdg-quality-education": "#C5192D",
        "sdg-gender-equality": "#FF3A21",
        "sdg-clean-water": "#26BDE2",
        "sdg-affordable-energy": "#FCC30B",
        "sdg-decent-work": "#A21942",
        "sdg-industry-innovation": "#FD6925",
        "sdg-reduced-inequalities": "#DD1367",
        "sdg-sustainable-cities": "#FD9D24",
        "sdg-responsible-consumption": "#BF8B2E",
        "sdg-climate-action": "#3F7E44",
        "sdg-life-below-water": "#0A97D9",
        "sdg-life-on-land": "#56C02B",
        "sdg-peace-justice": "#00689D",
        "sdg-partnerships": "#19486A",
      },
      boxShadow: {
        brutal: "2px 2px 0px 0px rgba(0, 0, 0, 1)",
        "brutal-sm": "1px 1px 0px 0px rgba(0, 0, 0, 1)",
        "brutal-lg": "3px 3px 0px 0px rgba(0, 0, 0, 1)",
      },
      spacing: {
        gutter: "24px",
        base: "8px",
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "body-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-xl": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-md": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg-mobile": ["Atkinson Hyperlegible Next", "sans-serif"],
        "headline-lg": ["Atkinson Hyperlegible Next", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "label-bold": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
